Category.create(name: "Books")
Category.create(name: "Bikes")
Category.create(name: "Cars")
Category.create(name: "Instruments")
Category.create(name: "Furniture")
Category.create(name: "Electronics")
